"use client";
import { X, TrendingUp, TrendingDown, Award, Star, AlertTriangle, CheckCircle, XCircle, Copy, Check, BarChart3, Clock, Calendar } from 'lucide-react';
import { useState } from 'react';
import { useTheme } from './ThemeProvider';
import { useLanguage } from './LanguageProvider';

export default function PostTradeResultModal({
  isOpen,
  onClose,
  analysis,
  trade,
  image
}) {
  const { isDark } = useTheme();
  const { language } = useLanguage();
  const [copied, setCopied] = useState(false);

  const labels = {
    es: {
      title: 'Análisis Post-Trade',
      close: 'Cerrar',
      asset: 'Activo',
      direction: 'Dirección',
      result: 'Resultado',
      entry: 'Entrada',
      exit: 'Salida',
      copyAnalysis: 'Copiar análisis',
      copied: 'Copiado',
      disclaimer: 'Este análisis es solo para fines educativos. Úsalo para mejorar tu trading.',
      generatedBy: 'Generado por IA',
      gradeA: 'Ejecución excelente',
      gradeB: 'Buena ejecución',
      gradeC: 'Ejecución regular',
      gradeD: 'Necesita mejorar',
    },
    en: {
      title: 'Post-Trade Analysis',
      close: 'Close',
      asset: 'Asset',
      direction: 'Direction',
      result: 'Result',
      entry: 'Entry',
      exit: 'Exit',
      copyAnalysis: 'Copy analysis',
      copied: 'Copied',
      disclaimer: 'This analysis is for educational purposes only. Use it to improve your trading.',
      generatedBy: 'Generated by AI',
      gradeA: 'Excellent execution',
      gradeB: 'Good execution',
      gradeC: 'Average execution',
      gradeD: 'Needs improvement',
    },
  };
  const t = labels[language];

  if (!isOpen) return null;

  const handleCopyAnalysis = async () => {
    if (analysis) {
      await navigator.clipboard.writeText(analysis);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // Extract grade from analysis
  const extractGrade = () => {
    if (!analysis) return null;
    const gradeMatch = analysis.match(/CALIFICACIÓN[:\s]*([ABCD])|GRADE[:\s]*([ABCD])|##\s*📊\s*CALIFICACIÓN[:\s]*([ABCD])/i);
    if (gradeMatch) {
      return gradeMatch[1] || gradeMatch[2] || gradeMatch[3];
    }
    // Try to find grade emoji pattern
    if (analysis.includes('🏆') && (analysis.includes('A') || analysis.includes('Excelente'))) return 'A';
    if (analysis.includes('✅') && (analysis.includes('B') || analysis.includes('Buena'))) return 'B';
    if (analysis.includes('⚠️') && (analysis.includes('C') || analysis.includes('Regular'))) return 'C';
    if (analysis.includes('❌') && (analysis.includes('D') || analysis.includes('Mejorar'))) return 'D';
    return null;
  };

  const grade = extractGrade();

  const getGradeStyle = (g) => {
    switch(g) {
      case 'A': return { bg: 'bg-green-500', text: 'text-green-500', bgLight: isDark ? 'bg-green-500/20' : 'bg-green-100' };
      case 'B': return { bg: 'bg-blue-500', text: 'text-blue-500', bgLight: isDark ? 'bg-blue-500/20' : 'bg-blue-100' };
      case 'C': return { bg: 'bg-amber-500', text: 'text-amber-500', bgLight: isDark ? 'bg-amber-500/20' : 'bg-amber-100' };
      case 'D': return { bg: 'bg-red-500', text: 'text-red-500', bgLight: isDark ? 'bg-red-500/20' : 'bg-red-100' };
      default: return { bg: 'bg-slate-500', text: 'text-slate-500', bgLight: isDark ? 'bg-slate-500/20' : 'bg-slate-100' };
    }
  };

  const gradeStyle = getGradeStyle(grade);

  const getGradeLabel = (g) => {
    switch(g) {
      case 'A': return t.gradeA;
      case 'B': return t.gradeB;
      case 'C': return t.gradeC;
      case 'D': return t.gradeD;
      default: return '';
    }
  };

  // Render markdown-like text with basic formatting
  const renderFormattedText = (text) => {
    if (!text) return null;

    const lines = text.split('\n');

    return lines.map((line, index) => {
      // Headers (##)
      if (line.startsWith('## ')) {
        return (
          <h3 key={index} className={`text-base font-bold mt-4 mb-2 pb-2 border-b ${
            isDark ? 'text-blue-400 border-blue-500/30' : 'text-blue-600 border-blue-200'
          }`}>
            {line.replace('## ', '')}
          </h3>
        );
      }

      // Headers (###)
      if (line.startsWith('### ')) {
        return (
          <h4 key={index} className={`text-sm font-bold mt-3 mb-1.5 ${
            isDark ? 'text-slate-300' : 'text-slate-700'
          }`}>
            {line.replace('### ', '')}
          </h4>
        );
      }

      // Bold text with **
      if (line.includes('**')) {
        const parts = line.split(/\*\*(.+?)\*\*/g);
        return (
          <p key={index} className={`text-sm mb-1.5 leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
            {parts.map((part, i) =>
              i % 2 === 1 ? (
                <strong key={i} className={isDark ? 'text-white' : 'text-slate-900'}>{part}</strong>
              ) : part
            )}
          </p>
        );
      }

      // Numbered list
      if (/^\d+\.\s/.test(line.trim())) {
        return (
          <p key={index} className={`text-sm mb-1 ml-2 ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
            {line}
          </p>
        );
      }

      // Bullet points
      if (line.trim().startsWith('- ') || line.trim().startsWith('• ')) {
        return (
          <p key={index} className={`text-sm mb-1 ml-3 flex items-start gap-2 ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
            <span className="text-blue-500 mt-0.5">•</span>
            <span>{line.replace(/^[\s]*[-•]\s*/, '')}</span>
          </p>
        );
      }

      // Horizontal rule
      if (line.trim() === '---') {
        return <hr key={index} className={`my-3 ${isDark ? 'border-slate-700' : 'border-slate-200'}`} />;
      }

      // Empty line
      if (line.trim() === '') {
        return <div key={index} className="h-2" />;
      }

      // Regular text
      return (
        <p key={index} className={`text-sm mb-1 leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
          {line}
        </p>
      );
    });
  };

  const isWin = trade?.res >= 0;

  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 pt-16 sm:pt-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className={`relative w-full max-w-2xl max-h-[85vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col ${
        isDark ? 'bg-slate-800' : 'bg-white'
      }`}>
        {/* Header */}
        <div className={`flex-shrink-0 px-4 py-3 border-b flex items-center justify-between ${
          isDark
            ? 'bg-gradient-to-r from-blue-900/50 to-cyan-900/50 border-blue-500/30'
            : 'bg-gradient-to-r from-blue-50 to-cyan-50 border-blue-200'
        }`}>
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isDark ? 'bg-blue-500/20' : 'bg-blue-100'}`}>
              <Award size={20} className="text-blue-500" />
            </div>
            <div>
              <h2 className={`font-bold text-base ${isDark ? 'text-white' : 'text-slate-800'}`}>
                {t.title}
              </h2>
              <p className={`text-[10px] ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                {t.generatedBy}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className={`p-2 rounded-xl transition-colors ${
              isDark ? 'hover:bg-white/10 text-slate-400' : 'hover:bg-slate-100 text-slate-500'
            }`}
          >
            <X size={20} />
          </button>
        </div>

        {/* Image Preview */}
        {image && (
          <div className={`flex-shrink-0 px-4 py-3 border-b ${isDark ? 'bg-slate-900/50 border-slate-700' : 'bg-slate-100 border-slate-200'}`}>
            <div className="relative rounded-lg overflow-hidden border-2 border-blue-500/50">
              <img
                src={image.data}
                alt="Trade chart"
                className="w-full h-40 object-cover"
              />
              {image.temporalidad && (
                <span className={`absolute bottom-1 left-1 px-2 py-0.5 rounded text-[10px] font-bold ${
                  isDark ? 'bg-slate-900/80 text-blue-400' : 'bg-white/90 text-blue-600'
                }`}>
                  {image.temporalidad}
                </span>
              )}
            </div>
          </div>
        )}

        {/* Trade Info Bar with Grade */}
        <div className={`flex-shrink-0 px-4 py-3 flex flex-wrap items-center gap-2 border-b ${
          isDark ? 'bg-slate-700/50 border-slate-700' : 'bg-slate-50 border-slate-200'
        }`}>
          {/* Grade Badge */}
          {grade && (
            <div className={`flex items-center gap-2 px-3 py-1.5 rounded-xl ${gradeStyle.bgLight}`}>
              <div className={`w-8 h-8 rounded-lg ${gradeStyle.bg} flex items-center justify-center`}>
                <span className="text-white font-black text-lg">{grade}</span>
              </div>
              <div>
                <p className={`text-[10px] font-bold uppercase ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                  {language === 'es' ? 'Calificación' : 'Grade'}
                </p>
                <p className={`text-xs font-bold ${gradeStyle.text}`}>
                  {getGradeLabel(grade)}
                </p>
              </div>
            </div>
          )}

          {trade?.activo && (
            <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold ${
              isDark ? 'bg-blue-500/20 text-blue-400' : 'bg-blue-100 text-blue-600'
            }`}>
              <BarChart3 size={12} />
              {trade.activo}
            </span>
          )}
          {trade?.dir && (
            <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold ${
              trade.dir === 'Long'
                ? isDark ? 'bg-green-500/20 text-green-400' : 'bg-green-100 text-green-600'
                : isDark ? 'bg-red-500/20 text-red-400' : 'bg-red-100 text-red-600'
            }`}>
              {trade.dir === 'Long' ? <TrendingUp size={12} /> : <TrendingDown size={12} />}
              {trade.dir}
            </span>
          )}
          <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold ${
            isWin
              ? isDark ? 'bg-green-500/20 text-green-400' : 'bg-green-100 text-green-600'
              : isDark ? 'bg-red-500/20 text-red-400' : 'bg-red-100 text-red-600'
          }`}>
            {isWin ? <CheckCircle size={12} /> : <XCircle size={12} />}
            {isWin ? '+' : ''}${trade?.res?.toFixed(2) || '0.00'}
          </span>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-4 py-4">
          {analysis ? (
            <div className="space-y-1">
              {renderFormattedText(analysis)}
            </div>
          ) : (
            <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
              {language === 'es' ? 'Sin análisis disponible' : 'No analysis available'}
            </p>
          )}

          {/* Disclaimer inside content so it scrolls */}
          <div className={`mt-4 p-3 rounded-xl ${isDark ? 'bg-blue-500/10 border border-blue-500/20' : 'bg-blue-50 border border-blue-200'}`}>
            <p className={`text-[10px] ${isDark ? 'text-blue-400/80' : 'text-blue-600'}`}>
              💡 {t.disclaimer}
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className={`flex-shrink-0 px-4 py-3 border-t flex items-center justify-end gap-2 ${
          isDark ? 'bg-slate-800 border-slate-700' : 'bg-white border-slate-200'
        }`}>
          <button
            onClick={handleCopyAnalysis}
            className={`px-4 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-colors ${
              copied
                ? 'bg-green-500 text-white'
                : isDark
                  ? 'bg-slate-700 hover:bg-slate-600 text-slate-300'
                  : 'bg-slate-100 hover:bg-slate-200 text-slate-600'
            }`}
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? t.copied : t.copyAnalysis}
          </button>
          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-xl text-xs font-bold bg-blue-500 hover:bg-blue-600 text-white transition-colors"
          >
            {t.close}
          </button>
        </div>
      </div>
    </div>
  );
}
