"use client";
import { X, TrendingUp, TrendingDown, AlertTriangle, Target, Shield, ChevronRight, Clock, Globe, BarChart3, Lightbulb, Copy, Check } from 'lucide-react';
import { useState } from 'react';
import { useTheme } from './ThemeProvider';
import { useLanguage } from './LanguageProvider';

export default function PreTradeResultModal({
  isOpen,
  onClose,
  analysis,
  asset,
  direction,
  session,
  timeframe,
  preTradeImages = []
}) {
  const { isDark } = useTheme();
  const { language } = useLanguage();
  const [copied, setCopied] = useState(false);

  const labels = {
    es: {
      title: 'Análisis Pre-Trade',
      close: 'Cerrar',
      asset: 'Activo',
      direction: 'Dirección',
      session: 'Sesión',
      timeframe: 'Temporalidad',
      copyLevels: 'Copiar niveles',
      copied: 'Copiado',
      disclaimer: 'Este análisis es solo para fines educativos. No constituye asesoramiento financiero.',
      generatedBy: 'Generado por IA',
      images: 'imágenes analizadas',
    },
    en: {
      title: 'Pre-Trade Analysis',
      close: 'Close',
      asset: 'Asset',
      direction: 'Direction',
      session: 'Session',
      timeframe: 'Timeframe',
      copyLevels: 'Copy levels',
      copied: 'Copied',
      disclaimer: 'This analysis is for educational purposes only. It does not constitute financial advice.',
      generatedBy: 'Generated by AI',
      images: 'images analyzed',
    },
  };
  const t = labels[language];

  if (!isOpen) return null;

  // Extract price levels from analysis text for copy functionality
  const extractLevels = () => {
    const text = analysis || '';
    const lines = text.split('\n');
    const levelLines = lines.filter(line =>
      line.includes('Entrada:') ||
      line.includes('Entry:') ||
      line.includes('Stop Loss:') ||
      line.includes('TP1:') ||
      line.includes('TP2:') ||
      line.includes('TP3:')
    );
    return levelLines.join('\n');
  };

  const handleCopyLevels = async () => {
    const levels = extractLevels();
    if (levels) {
      await navigator.clipboard.writeText(levels);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // Parse and format analysis with emojis
  const formatAnalysis = (text) => {
    if (!text) return null;

    // Add emojis to key sections
    let formatted = text
      // Headers and sections
      .replace(/##\s*ANÁLISIS DEL SETUP/gi, '## 🔍 ANÁLISIS DEL SETUP')
      .replace(/##\s*SETUP ANALYSIS/gi, '## 🔍 SETUP ANALYSIS')
      .replace(/##\s*📊\s*IDEA DE TRADE/gi, '## 💡 IDEA DE TRADE')
      .replace(/##\s*📊\s*TRADE IDEA/gi, '## 💡 TRADE IDEA')
      // Signals
      .replace(/\*\*Señales a favor\*\*/gi, '**✅ Señales a favor**')
      .replace(/\*\*Signals in favor\*\*/gi, '**✅ Signals in favor**')
      .replace(/\*\*Señales en contra\*\*/gi, '**⚠️ Señales en contra**')
      .replace(/\*\*Signals against\*\*/gi, '**⚠️ Signals against**')
      // Sentiment
      .replace(/\*\*Sentimiento de mercado\*\*/gi, '**📰 Sentimiento de mercado**')
      .replace(/\*\*Market sentiment\*\*/gi, '**📰 Market sentiment**')
      // Direction
      .replace(/\*\*Dirección sugerida:\*\*\s*LONG/gi, '**📈 Dirección sugerida:** LONG')
      .replace(/\*\*Suggested direction:\*\*\s*LONG/gi, '**📈 Suggested direction:** LONG')
      .replace(/\*\*Dirección sugerida:\*\*\s*SHORT/gi, '**📉 Dirección sugerida:** SHORT')
      .replace(/\*\*Suggested direction:\*\*\s*SHORT/gi, '**📉 Suggested direction:** SHORT')
      // Risk/Reward
      .replace(/\*\*Ratio Riesgo\/Beneficio:\*\*/gi, '**⚖️ Ratio Riesgo/Beneficio:**')
      .replace(/\*\*Risk\/Reward Ratio:\*\*/gi, '**⚖️ Risk/Reward Ratio:**')
      // Management
      .replace(/\*\*Gestión sugerida:\*\*/gi, '**🎯 Gestión sugerida:**')
      .replace(/\*\*Suggested management:\*\*/gi, '**🎯 Suggested management:**')
      // History
      .replace(/\*\*Basado en tu historial\*\*/gi, '**📚 Basado en tu historial**')
      .replace(/\*\*Based on your history\*\*/gi, '**📚 Based on your history**');

    return formatted;
  };

  // Render markdown-like text with basic formatting
  const renderFormattedText = (text) => {
    if (!text) return null;

    const lines = text.split('\n');

    return lines.map((line, index) => {
      // Headers (##)
      if (line.startsWith('## ')) {
        return (
          <h3 key={index} className={`text-base font-bold mt-4 mb-2 pb-2 border-b ${
            isDark ? 'text-purple-400 border-purple-500/30' : 'text-purple-600 border-purple-200'
          }`}>
            {line.replace('## ', '')}
          </h3>
        );
      }

      // Bold text with **
      if (line.includes('**')) {
        const parts = line.split(/\*\*(.+?)\*\*/g);
        return (
          <p key={index} className={`text-sm mb-1.5 leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
            {parts.map((part, i) =>
              i % 2 === 1 ? (
                <strong key={i} className={isDark ? 'text-white' : 'text-slate-900'}>{part}</strong>
              ) : part
            )}
          </p>
        );
      }

      // Bullet points
      if (line.trim().startsWith('- ') || line.trim().startsWith('• ')) {
        return (
          <p key={index} className={`text-sm mb-1 ml-3 flex items-start gap-2 ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
            <ChevronRight size={14} className="mt-1 flex-shrink-0 text-purple-500" />
            <span>{line.replace(/^[\s]*[-•]\s*/, '')}</span>
          </p>
        );
      }

      // Horizontal rule
      if (line.trim() === '---') {
        return <hr key={index} className={`my-3 ${isDark ? 'border-slate-700' : 'border-slate-200'}`} />;
      }

      // Empty line
      if (line.trim() === '') {
        return <div key={index} className="h-2" />;
      }

      // Regular text
      return (
        <p key={index} className={`text-sm mb-1 leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
          {line}
        </p>
      );
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 pt-16 sm:pt-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className={`relative w-full max-w-2xl max-h-[85vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col ${
        isDark ? 'bg-slate-800' : 'bg-white'
      }`}>
        {/* Header */}
        <div className={`flex-shrink-0 px-4 py-3 border-b flex items-center justify-between ${
          isDark
            ? 'bg-gradient-to-r from-purple-900/50 to-blue-900/50 border-purple-500/30'
            : 'bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200'
        }`}>
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isDark ? 'bg-purple-500/20' : 'bg-purple-100'}`}>
              <Lightbulb size={20} className="text-purple-500" />
            </div>
            <div>
              <h2 className={`font-bold text-base ${isDark ? 'text-white' : 'text-slate-800'}`}>
                {t.title}
              </h2>
              <p className={`text-[10px] ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                {t.generatedBy} • {preTradeImages.length} {t.images}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className={`p-2 rounded-xl transition-colors ${
              isDark ? 'hover:bg-white/10 text-slate-400' : 'hover:bg-slate-100 text-slate-500'
            }`}
          >
            <X size={20} />
          </button>
        </div>

        {/* Images Preview */}
        {preTradeImages && preTradeImages.length > 0 && (
          <div className={`flex-shrink-0 px-4 py-3 border-b ${isDark ? 'bg-slate-900/50 border-slate-700' : 'bg-slate-100 border-slate-200'}`}>
            <div className={`grid gap-2 ${
              preTradeImages.length === 1 ? 'grid-cols-1' :
              preTradeImages.length === 2 ? 'grid-cols-2' : 'grid-cols-3'
            }`}>
              {preTradeImages.map((img, index) => (
                <div key={index} className="relative rounded-lg overflow-hidden border-2 border-purple-500/50">
                  <img
                    src={img.base64}
                    alt={`Chart ${index + 1}`}
                    className="w-full h-32 object-cover"
                  />
                  <span className={`absolute bottom-1 left-1 px-2 py-0.5 rounded text-[10px] font-bold ${
                    isDark ? 'bg-slate-900/80 text-purple-400' : 'bg-white/90 text-purple-600'
                  }`}>
                    {img.timeframe}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Trade Info Bar */}
        <div className={`flex-shrink-0 px-4 py-2 flex flex-wrap gap-2 border-b ${
          isDark ? 'bg-slate-700/50 border-slate-700' : 'bg-slate-50 border-slate-200'
        }`}>
          {asset && (
            <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold ${
              isDark ? 'bg-blue-500/20 text-blue-400' : 'bg-blue-100 text-blue-600'
            }`}>
              <BarChart3 size={12} />
              {asset}
            </span>
          )}
          {direction && (
            <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold ${
              direction === 'Long'
                ? isDark ? 'bg-green-500/20 text-green-400' : 'bg-green-100 text-green-600'
                : isDark ? 'bg-red-500/20 text-red-400' : 'bg-red-100 text-red-600'
            }`}>
              {direction === 'Long' ? <TrendingUp size={12} /> : <TrendingDown size={12} />}
              {direction}
            </span>
          )}
          {timeframe && (
            <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold ${
              isDark ? 'bg-purple-500/20 text-purple-400' : 'bg-purple-100 text-purple-600'
            }`}>
              <Clock size={12} />
              {timeframe}
            </span>
          )}
          {session && (
            <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold ${
              isDark ? 'bg-amber-500/20 text-amber-400' : 'bg-amber-100 text-amber-600'
            }`}>
              <Globe size={12} />
              {session}
            </span>
          )}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-4 py-4">
          {analysis ? (
            <div className="space-y-1">
              {renderFormattedText(formatAnalysis(analysis))}
            </div>
          ) : (
            <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
              {language === 'es' ? 'Sin análisis disponible' : 'No analysis available'}
            </p>
          )}

          {/* Disclaimer inside content so it scrolls */}
          <div className={`mt-4 p-3 rounded-xl ${isDark ? 'bg-amber-500/10 border border-amber-500/20' : 'bg-amber-50 border border-amber-200'}`}>
            <p className={`text-[10px] ${isDark ? 'text-amber-400/80' : 'text-amber-600'}`}>
              ⚠️ {t.disclaimer}
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className={`flex-shrink-0 px-4 py-3 border-t flex items-center justify-end gap-2 ${
          isDark ? 'bg-slate-800 border-slate-700' : 'bg-white border-slate-200'
        }`}>
          <button
            onClick={handleCopyLevels}
            className={`px-4 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-colors ${
              copied
                ? 'bg-green-500 text-white'
                : isDark
                  ? 'bg-slate-700 hover:bg-slate-600 text-slate-300'
                  : 'bg-slate-100 hover:bg-slate-200 text-slate-600'
            }`}
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? t.copied : t.copyLevels}
          </button>
          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-xl text-xs font-bold bg-purple-500 hover:bg-purple-600 text-white transition-colors"
          >
            {t.close}
          </button>
        </div>
      </div>
    </div>
  );
}
